# Generated by Django 4.2 on 2023-04-21 15:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_user_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_image',
            field=models.URLField(default='', validators=[django.core.validators.URLValidator()]),
            preserve_default=False,
        ),
    ]
