# Generated by Django 4.2 on 2023-04-22 10:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='image',
            field=models.URLField(default='', validators=[django.core.validators.URLValidator()]),
            preserve_default=False,
        ),
    ]
