# Generated by Django 4.2 on 2023-04-22 10:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0002_animal_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='image',
            field=models.URLField(max_length=1000, validators=[django.core.validators.URLValidator()]),
        ),
    ]
