# Generated by Django 4.2 on 2023-04-22 14:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sightings', '0002_sighting_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='sighting',
            name='image',
            field=models.URLField(default='', max_length=1000, validators=[django.core.validators.URLValidator()]),
            preserve_default=False,
        ),
    ]
